### ISSUE TITLE
Updating subscription filters on the fly

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/jetstream-legacy#2]
Previous discussion: https://bsky.app/profile/did:plc:ia76kvnndjutgedggx2ibrem/post/3l4nhbqttj25t

It would be neat if we can send a JSON message to the socket that'd allow for changing filters on the fly:

```ts
interface UpdateFiltersMessage {
  type: 'filter';
  wantedCollections: string[];
  wantedDids: string[];
}
```

Users relying on dynamically changing filters (e.g. watching a specific portion of users or collections at a time) could change them without having to reconnect and potentially replay any past events. It'd also mean being able to make full use of the 10k subscribed DIDs limit (it's not possible to reach that amount due to URI length limit)

Additionally, there could be an option where sending this message is required before any incoming messages could be retrieved, perhaps something like `?requireHello=true`, not sure how this'd go with replaying past events though since it'd have to be deferred.

**Comment by moll-dev** [comment]
This would also be a good starting point for Jaz's compression handshake too.

**Comment by moll-dev** [comment]
NVM I see they handle compression on the initial WS request. 
```
	// Check if the user wants zstd compression
	socketEncoding := c.Request().Header.Get("Socket-Encoding")
	compress := strings.Contains(socketEncoding, "zstd")
```

**Comment by jazware** [comment]
Readme has been updated with specs on Subscriber Sourced Messages including the Options Update message and the public instance has been redeployed.
