### ISSUE TITLE
Feature Request: `mentionedDids`

### ISSUE THREAD

**Issue by mattbrailsford** [bluesky-social/jetstream-legacy#20]
I'm creating a bot that responds to being mentioned and from what I can tell my only current option is to monitor the full posts collection for any posts that mention my bot. This sounds like a heck of a lot of wasted bandwidth.

It would be really cool if like the `wantedDids` we could have something like `mentionedDids` to filter posts to just those that mention a specific account.

**Comment by simeon-simsoft** [comment]
This would be a very useful feature.. also to be able to request # mentions which don't have a DID

**Comment by jazware** [comment]
See https://github.com/bluesky-social/jetstream/issues/15#issuecomment-2443224707

This is likely outside the scope of Jetstream for now, sorry.

**Comment by mattbrailsford** [comment]
I thought that might be the case after looking at the code. No worries. Hopefully it’ll come in another API at some point 👍🏻
