### ISSUE TITLE
No new account creation events in stream

### ISSUE THREAD

**Issue by flo-bit** [bluesky-social/jetstream-legacy#25]
Since some point yesterday, I'm not receiving any events with new account creations.

this example code only prints "Connected to BlueSky WebSocket" and nothing else, when it should print all new account events (and it worked yesterday).

```js
import WebSocket from 'ws';

// WebSocket URL from BlueSky
const url = 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post';

const ws = new WebSocket(url);

ws.on('message', (data) => {
	const json = JSON.parse(data);
	if(json.kind === 'account') console.log(json);
});

ws.on('open', () => {
    console.log('Connected to BlueSky WebSocket');
});

ws.on('error', (error) => {
    console.error('WebSocket error:', error);
});

ws.on('close', () => {
    console.log('WebSocket connection closed');
});
```

**Comment by hbarb-dev** [comment]
Facing same issue. Specifically, no events of "kind":"account" are being emitted

**Comment by flo-bit** [comment]
someone opened a pull request with a fix on my repo, where I had this problem:

```js
import WebSocket from 'ws';

// add wantedCollections=app.bsky.actor.profile
const url = 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.actor.profile';

const ws = new WebSocket(url);

ws.on('message', (data) => {
	const json = JSON.parse(data);
	if (json.kind !== 'commit') return;

	// check for collection and operation
	if(json.commit.collection === 'app.bsky.actor.profile' &&
		json.commit.operation === 'create') {
		console.log("new user"
	}
});
```

it seems the readme is not quite up to date anymore?

**Comment by hbarb-dev** [comment]
> someone opened a pull request with a fix on my repo, where I had this problem:
> 
> ```js
> import WebSocket from 'ws';
> 
> // add wantedCollections=app.bsky.actor.profile
> const url = 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.actor.profile';
> 
> const ws = new WebSocket(url);
> 
> ws.on('message', (data) => {
> 	const json = JSON.parse(data);
> 	if (json.kind !== 'commit') return;
> 
> 	// check for collection and operation
> 	if(json.commit.collection === 'app.bsky.actor.profile' &&
> 		json.commit.operation === 'create') {
> 		console.log("new user"
> 	}
> });
> ```
> 
> it seems the readme is not quite up to date anymore?

I see, but there are still no account events ? "kind": "account" events are used for user deletions also

**Comment by cullophid** [comment]
Just came to report the same issue :)

**Comment by jazware** [comment]
Sorry, this was a bug with upstream Relay stuff that got fixed after a few days. Should be good now. Thanks!
