### ISSUE TITLE
[Feature Request] Include subject DID in depete events

### ISSUE THREAD

**Issue by cihantas** [bluesky-social/jetstream-legacy#29]
**Problem:**
Delete events miss the subject DID. Consequently, tracking `delete` events such as `app.bsky.graph.follow` on a set of profiles is complicated. 

**Solution:**
Include the subject DID in deletion events by default or allow a flag to subscribe to fat deletion events.

I'm happy to provide a PR, if you confirm this has a chance to be merged.

**Example:**
We want to track `create` and `delete` events on a set of profiles for various events. Following the example of `app.bsky.graph.follow` events, we have to:

1) Consume the whole Jetstream feed unfiltered, because `wantedDids` applies to the follower, not the profile being followed.
2) Finding relevant follow `create` events is straightforward. We only match the subject DID against our list of profile DIDs to track.
3) Delete events do not have a subject DID. We can't ask: "Does this event belong to one of the profiles we're monitoring?". Instead we have to ask "For all our tracked profiles and their latest follower events, does this rkey match any of these events?". This severely complicates analytics programs, because we now have to track the `rkey` as an indirect data point to match against. Additionally, if we track events on a large number of profiles, with a large number of followers, matching `rkey` requires m * n checks, instead of m.

**Additional Context:**
I'm working with a company that is prototyping an analytics tool and wants to track events on specific profiles.

**Comment by jazware** [comment]
There is literally no way to do that without indexing every single event that comes in and storing it until it's deleted. Unfortunately you'll have to do the indexing and storage on your side, sorry.
