### ISSUE TITLE
Include subject DID on follow and block deletion records

### ISSUE THREAD

**Issue by gnito-org** [bluesky-social/jetstream-legacy#37]
If possible, please include the subject DID in the records of follow and block deletions.

There are use cases where one wants to know who was unfollowed and who was unblocked.

At the time of the deletion record appearing in the firehose, the actual follow / block record has been deleted, and one cannot use the rkey to retrieve the subject DID any longer.

**Comment by jazware** [comment]
See https://github.com/bluesky-social/jetstream/issues/29
