### ISSUE TITLE
Some commit events are missing commit object details

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/jetstream-legacy#5]
They all seem to be accounts from Bridgy, some DIDs:

```
did:plc:dzfsd3qxli7y3urrfctxbfcw
did:plc:7xnr5dyt5nq2zmxu3leug42u
did:plc:yq6ecjswdcc45g3nd3zu5uau
did:plc:fhjsdbo2dwj3jgieya3s37fw
```

E.g. events come like this:

```
{"did"=>"did:plc:dzfsd3qxli7y3urrfctxbfcw", "time_us"=>1727916575716667, "type"=>"com"}
{"did"=>"did:plc:7xnr5dyt5nq2zmxu3leug42u", "time_us"=>1727916643242871, "type"=>"com"}
{"did"=>"did:plc:yq6ecjswdcc45g3nd3zu5uau", "time_us"=>1727916716244004, "type"=>"com"}
{"did"=>"did:plc:dzfsd3qxli7y3urrfctxbfcw", "time_us"=>1727916791154716, "type"=>"com"}
{"did"=>"did:plc:dzfsd3qxli7y3urrfctxbfcw", "time_us"=>1727916796666440, "type"=>"com"}
{"did"=>"did:plc:dzfsd3qxli7y3urrfctxbfcw", "time_us"=>1727916819564531, "type"=>"com"}
{"did"=>"did:plc:dzfsd3qxli7y3urrfctxbfcw", "time_us"=>1727917019688644, "type"=>"com"}
{"did"=>"did:plc:fhjsdbo2dwj3jgieya3s37fw", "time_us"=>1727917100985995, "type"=>"com"}
```

So there's the `type` set to `com`, but there's no `commit` field…

**Comment by jazware** [comment]
Should be resolved by https://github.com/bluesky-social/jetstream/commit/5b3e24d172ad6ba920545a8bb3632831a62b286f

**Comment by mackuba** [comment]
Yup, doesn't seem to be happening anymore.

Though tbh I don't really understand why this specific change fixes this :) Both `break` and `continue` (if these work in Go like everywhere else) skip the current interation of the loop iterating over operations, so in both cases `e.Commit` should not be assigned but also `e` not saved, right?…

**Comment by jazware** [comment]
Break in Go breaks out of an if statement in this case but means we fall through to still sequence and send the event. Continue tells it to not emit an event for that op and go to the next op in the event.

**Comment by mackuba** [comment]
Ahhh, because there's a `switch` and `break` here just jumps out of the `switch` and not from the loop…

**Comment by jazware** [comment]
Err, yeah it breaks out of the closest control structure that takes a break, which is kind of a PITA at times lol.

**Comment by mackuba** [comment]
It definitely feels confusing that `break` and `continue` aren't "symmetrical" here in the way that they don't jump out of the same block just skipping or not skipping the next iterations… I had to check, but it looks like it's the same in at least JavaScript and Swift.
