### ISSUE TITLE
403 for browser connections

### ISSUE THREAD

**Issue by kotx** [bluesky-social/jetstream-legacy#6]
When connecting to the provided 4 jetstream instances via a browser, the upgrade requests returns a 403.
```
new WebSocket("wss://jetstream1.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post");
```
![image](https://github.com/user-attachments/assets/a65dae51-7e9e-406d-bbe4-113760a42839)

(Unfortunately can't view the response content from Firefox)

**Comment by jazware** [comment]
I think this violates the content security policy from whatever site you have active when trying to load this from the browser. There isn't anything on the server that should be sending back a 403.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

The CSP is set by i.e. GitHub.com if you open the console on a github page and restricts what external sites you're allowed to load data from. This isn't configured on Jetstream's side.

**Comment by kotx** [comment]
I've set up a [proxy](https://dash.deno.com/playground/wide-cow-97) (to the official jetstream instance) on Deno cloud and it works fine: `new WebSocket("wss://wide-cow-97.deno.dev/subscribe?wantedCollections=app.bsky.feed.post");`. So this seems to be a Jetstream-side issue?

**Comment by kotx** [comment]
This is what a CSP blockage looks like. Different from a 403.
<img width="677" alt="image" src="https://github.com/user-attachments/assets/e993f76d-26a1-4c66-a524-4b9626ab4c1d">

For the record, the proxy works and Jetstream doesn't in an about:blank page.

**Comment by jazware** [comment]
I've added a CORS policy and tweaked the HAProxy config a bit, wanna lmk if you're still seeing this?

**Comment by kotx** [comment]
Still seeing it unfortunately. Can repro this with:
```
% curl 'https://jetstream1.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Sec-WebSocket-Version: 13' -H 'Origin: https://google.com' -H 'Sec-WebSocket-Extensions: permessage-deflate' -H 'Sec-WebSocket-Key: pvMrsMunwma/ZNCNP3RSpw==' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive, Upgrade' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: websocket' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade: websocket'
Bad Request
```

**Comment by damz** [comment]
See the [Origin Considerations](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Origin_Considerations) section in the documentation for `github.com/gorilla/websocket`. You need an explicit `CheckOrigin` function in the upgrader configuration, as the default is restrictive:

> If the CheckOrigin field is nil, then the Upgrader uses a safe default: fail the handshake if the Origin request header is present and the Origin host is not equal to the Host request header.

**Comment by damz** [comment]
(Note that when testing with cURL, like above you need to specifically tell it to use HTTP/1.1, via the `--http1.1` option, because HTTP/2 doesn't support Websocket using the HTTP/1.1 upgrade semantics.)

**Comment by jazware** [comment]
Okay @kotx do you want to give it another try on `wss://jetstream.atproto.tools/subscribe`?

I've explicitly configured the CORS for the websocket upgrader that @damz mentioned and it should be running now.

Using the curl command you provided with `--http1.1` shows forbidden on the prod instances but works properly on my dev instance (which has the fix).

**Comment by kotx** [comment]
@ericvolp12 Works for me!

**Comment by jazware** [comment]
This should now be shipped to the prod Jetstream instances.
